services:
  postgres:
    container_name: postgres_crowd
    image: postgres:latest
    environment:
      DATABASE_URL: postgresql://admin:password@localhost:5432/postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local
