import { status } from "@prisma/client";

export const candidates = [
  {
    first_name: "Arne",
    last_name: "Alligator",
    email: "arne@alligator.com",
    position: "Luring Developer",
    current_status: status.contact,
  },
  {
    first_name: "Bosse",
    last_name: "Bus",
    email: "bosse@busig.com",
    position: "Prank Developer",
    current_status: status.contact,
  },
  {
    first_name: "Styrbjörn",
    last_name: "Stolpe",
    email: "styris@stolpeut.com",
    position: "Pole Developer",
    current_status: status.contact,
  },
  {
    first_name: "Karsten",
    last_name: "Kerstin",
    email: "karsten@kerstin.com",
    position: "IOS Developer",
    current_status: status.contact,
  },
  {
    first_name: "Helmut",
    last_name: "Mutti",
    email: "helmutmutti@yahoo.com",
    position: "Song Developer",
    current_status: status.dialogue,
  },
  {
    first_name: "Julio",
    last_name: "Iglesias",
    email: "julio@yahoo.com",
    position: "Emotion Developer",
    current_status: status.dialogue,
  },
  {
    first_name: "Enrique",
    last_name: "Iglesias",
    email: "enrique.iggy@google.com",
    position: "Jealous Developer",
    current_status: status.dialogue,
  },
  {
    first_name: "Curry",
    last_name: "Nam",
    email: "curry.iggy@google.com",
    position: "Hunger Developer",
    current_status: status.dialogue,
  },
  {
    first_name: "Kung",
    last_name: "Bore",
    email: "kungen@hovet.com",
    position: "Drill Developer",
    current_status: status.interview,
  },
  {
    first_name: "Kneten",
    last_name: "I Smeten",
    email: "kneten@knutte.com",
    position: "Pain Developer",
    current_status: status.interview,
  },
  {
    first_name: "Klimpen",
    last_name: "Knogjärn",
    email: "klimpen@knutte.com",
    position: "Pain Developer",
    current_status: status.interview,
  },
  {
    first_name: "Palle",
    last_name: "Kuling",
    email: "palla@kuling.com",
    position: "Apple Developer",
    current_status: status.offer,
  },
  {
    first_name: "Morran",
    last_name: "Morrhår",
    email: "morre@morran.com",
    position: "Happy Developer",
    current_status: status.offer,
  },
  {
    first_name: "Corny",
    last_name: "Dog",
    email: "corn@dog.com",
    position: "Corn Developer",
    current_status: status.offer,
  },
  {
    first_name: "Jussi",
    last_name: "Björling",
    email: "jussi@cat.com",
    position: "Juice Developer",
    current_status: status.offer,
  },
  {
    first_name: "Barry",
    last_name: "Bok",
    email: "barry@cat.com",
    position: "Book Developer",
    current_status: status.closed,
  },
];
